[toolchain]
# Keep in sync with Cargo.toml's `rust-version`.

# Copyright contributors to the openqasm-parser project

channel = "1.72.0"
components = [
  "cargo",
  "clippy",
  "rust-std",
  "rustc",
  "rustfmt",
]
