---
name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rust Format
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --release --verbose
    - name: Clippy
      run: cargo clippy --all-targets -- -D warnings -D clippy::dbg_macro
    - name: Run tests
      run: cargo test --verbose -- --skip sourcegen_ast --skip sourcegen_ast_nodes
