---
name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install Just
      run: cargo install just
    - name: Rust Format
      run: just ci
    - name: Check source generation
      run: just check_sourcegen

  msrv:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@1.79
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose --lib --tests
